import React, { Component } from 'react'
import { Link } from 'react-router-dom';
import { Helmet } from "react-helmet";  
import TagManager from 'react-gtm-module'; 
import Breadcrumb from '../../navbar/Breadcrumb';
import Banner1 from '../../../assets/images/blog/arvrwithmanufacturing.jpg';
import xrwithpharma from '../../../assets/images/blog/xrwithpharma.jpg';
import BlogSidebar from './BlogSidebar';

export class XrPharmaceutical_Blog extends Component {
  render() {
    const tagManagerArgs = {
        gtmId: 'GTM-P2QXCFZ'
    }
    TagManager.initialize(tagManagerArgs);
    return (
      <>
        <Helmet>  
            <title>XR – A medicine for the Pharmaceutical Industry</title> 
            <meta name="title" content="" />   
            <meta name="description" content="" />  
            <meta name="keywords" content="" />  
         </Helmet> 
         <div className="page-content">
            <div className="page-banner ovbl-dark parallax" style={{backgroundImage: "url("+Banner1+")"}}>
              <Breadcrumb heading="Pharmaceutical Industry" title="Pharmaceutical Industry" />
            </div>

            <div className="content-block">
                <div className="section-area section-sp2 bg-grey">
                    <div className="container">
                        <div className="row">
                                <div className="col-md-12 col-lg-8 col-xl-8 m-md-b50">
                                    <div className="blog-lg blog-single">
                                        <div className="action-box blog-lg">
                                            <img src={xrwithpharma} alt=""/>
                                        </div>
                                        <div className="info-bx">
                                            <div className="ttr-post-title">
                                                <h4 className="post-title">XR – A medicine for the Pharmaceutical Industry</h4>
                                            </div>
                                            <div className="ttr-post-text">
                                                <p>As per a report by Statista revenue generated by the global pharmaceutical market in 2019 was USD 1250 Billion, and North America is the largest driver of these revenues globally. As per some experts the growth in the sector had reached a saturation level and only now with the recent developments and technological innovations has the sector started to gain momentum. AR, VR, MR and XR technologies have led these innovations in technology by opening new gateways and challenging the established norms. There are plenty of applications for these technologies, which includes its use cases in marketing, sales, research and development, treatment, training and manufacturing (list non-exhaustive).</p>
                                                <p>Extended Reality or XR is an umbrella term which encapsulates AR, VR and MR technologies as a whole.</p>
                                                <h4>Regulations in Pharmaceutical Industry</h4>
                                                <p>Let’s face it, the pharmaceutical industry has the strictest regulatory frameworks, which are of course necessary when the lives of people are at stake directly. The pharmaceutical product lifecycle can extend up to 20-25 years starting from research and discovery to post approval stage. There is fierce competition and a rising demand for lowered prices of the drugs. This is where XR can significantly help organizations in cutting the costs, increasing the productivity and eventually leading to efficient processes in time. It offers to provide substantial technological support during most of the phases starting from research and development phase to eventually marketing to the consumers.</p>
                                                <p>As per one report Global AR and VR market in healthcare industry is expected to reach $10 billion by 2025 with a considerable CAGR of 36%.</p>
                                                <h4>Research and Design</h4>
                                                <p>XR enables the availability of a 3D virtual world wherein all design related tasks can be easily managed. Now you don’t have to make a real model or API for instance, for research and design purposes. You can now virtually interact with the 3D structures which substantially helps researchers during the design stages. Novartis for instance uses VR in their labs. With a particular software they created, the respective team could use VR headsets helping them virtually explore the protein world in 3D environment, to translate that information into meaningful research and design oriented decisions.</p>
                                                <h4>Treatment</h4>
                                                <p>With XR enabled technologies, the doctor can now potentially diagnose the patients by seeing the internals without having to insert a probe or without having to cut the external layers. It also helps in accurate predictions where the point of contact needs to be made, for e.g. while giving an injection, or making incisions, or conducting a surgery altogether.</p>
                                                <p>It also has great potential use cases while treating patients who have got a recent amputation for instance or for stroke patients as part of the physical therapy sessions. Psychological treatments can also use these technologies, and it has potential to help patients suffering with potential mental disorders, by offering a safe haven or conducting experiments in the various virtual world scenarios to help patients develop effective coping strategies.</p>
                                                <h4>Medical Diagnosis</h4>
                                                <p>There have been great technological advancements in the past such as MRI and CT scan for medical purposes related to diagnosis. Now with the XR technologies coming into the foray, diagnostics can be made much quicker. While MRI and CT scans for example play with 2 dimensional images and scans, XR can now lead the pack with better visualizations in 3D. What’s more, you can now interact with the 3D objects, make annotations, use interactive technologies like the Remote Assistance play, to explain and share the analysis and diagnostics part even remotely.</p>
                                                <p>With Augmented Reality for instance, the digital information can be made much interactive by superimposing the physical environment with the virtually generated objects.</p>
                                                <p>As per the Harvard Business Review article, and as per the image shown below (courtesy – HBR), doctors have the potential to see real-time metrics and critical operation related information which is displayed directly through the head-mounted displays or smart glasses for instance. Well, this is revolutionary!</p>
                                                <p>XR enabled solutions will help save lives and at the same time has the potential to reduce operational hazards and errors significantly.</p>
                                                <h4>Telemedicine</h4>
                                                <p>What is even more exciting is that fact that the same information displayed in the image above can also be shown in multi-user format and coupled with remote assistance, well the days are not far when medical experts from around the world are able to cater to the needs of the patients in the remotest of areas. Of course, we will allow certain medical practitioners in that region to perform those tasks at the behest of the inputs given by the medical experts. Some of the ground work is already in place. This would be particularly beneficial for the rural communities, as the medical care infrastructure is pretty in such communities.</p>
                                                <h4>Trainings and Education</h4>
                                                <p>As already emphasised, the entire XR driven approach helps organizations and its employees better be able to visualize challenging concepts much more easily and that too in an engaging way. The training in XR helps the employees/workers/doctors/nurses to make mistakes and learn in the virtual and immersive environment without having to worry about any real-world consequences. You learn, retain, react and act, and that too endlessly. At the same time, all your progress metrics are stored in a lively and interactive dashboard (Analytics Suite) for the decision makers in the organization to keep a track of, pertaining to the progress of their employees in meeting the learning outcomes, and at the same time, for the employees to know how they are performing, how they can do better, and how well are they retaining the content modules.</p>
                                                <p>Big organizations like Pfizer, J&J and many more are all shifting towards integrating XR solutions to meet their training needs. The cost effective solutions found through XR technology whilst ensuring that a deep pocket is not required to match L&D budgets with the outcomes they earmark, help organizations make the easy decision of deploying and using the XR led training modules. It is a win-win situation for all the stakeholders.</p>
                                                <h4>Marketing</h4>
                                                <p>With XR now the brands can differentiate themselves effectively. The customer engagement increases manifold when engaging technologies are deployed to further help them in all the stages of the consumer journey. Be it awareness stage, consideration stage, evaluation stage and even during the final decision making stage. Brands can now engage in telling immersive and meaningful stories. Storytelling cannot be more engaging than with the use of XR at your disposal.</p>
                                                <p>Organizations can now take part in delivering interactive product demos, be it at an exhibition, or during face to face client meetings. Novartis for instance has already deployed 360-degree VR technology for boosting their sales. Similar concepts can directly be utilized for helping patients and their families in understanding the complex procedures involved during an operation before hands.</p>
                                                <h4>Summary</h4>
                                                <p>As already shared, to sum it up XR can be used in a lot of ways for the pharma industry to help them in the value creation process.</p>
                                                <ul className='list-check'>
                                                    <li>Conduct digital meetings at ease</li>
                                                    <li>Engage in remote maintenance and upgradation</li>
                                                    <li>Conduct audits and inspections remotely</li>
                                                    <li>Revolutionize their training pedagogy</li>
                                                    <li>Effectively conduct SOP trainings</li>
                                                    <li>Review their process layouts more effectively</li>
                                                    <li>Indulge in better design and research practices</li>
                                                    <li>Scale their brand building efforts and differentiate at ease</li>
                                                    <li>Increase ROI tremendously</li>
                                                    <li>Achieve operational excellence</li>
                                                </ul>
                                                <p>We can realize this easily that how XR along with a combination of technologies it brings can be multifaceted in the pharma industry, by having potential use cases in almost all parts of the business. Many larger companies are already jumping on the bandwagon, make sure that you don’t lag behind. Find the right solutions for your business and scale new heights.</p>
                                            </div>

                                            <div className="ttr-divider bg-gray"><i className="icon-dot c-square"></i></div>
                                            <div className="ttr-post-meta d-flex">
                                                <div className="share-post ml-auto">
                                                    <ul className="social">
                                                        <li>Share:</li>
                                                        <li><Link to="#"><i className="fa fa-facebook"></i></Link></li>
                                                        <li><Link to="#"><i className="fa fa-twitter"></i></Link></li>
                                                        <li><Link to="#"><i className="fa fa-linkedin"></i></Link></li>
                                                        <li><Link to="#"><i className="fa fa-whatsapp "></i></Link></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <div className="col-md-12 col-lg-4 col-xl-4 sticky-top">
                                <BlogSidebar/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </>
    )
  }
}

export default XrPharmaceutical_Blog